import { Product } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-linen-set-1',
    name: 'LINEN SET',
    nameArabic: 'طقم كتان فاخر قطعتين',
    category: 'sets',
    categoryArabic: 'أطقم وسيتات',
    price: 450.0,
    discountPrice: 420.0,
    stockQuantity: 28,
    colors: [
      { name: 'Oatmeal Beige', nameArabic: 'بيج كشمير', hex: '#DCC9A6' },
      { name: 'Pure White', nameArabic: 'أبيض نقي', hex: '#FFFFFF' },
      { name: 'Onyx Black', nameArabic: 'أسود ملكي', hex: '#1F1F1F' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    specs: {
      fabric: '100% Organic French Linen',
      fabricArabic: 'كتان فرنسي عضوي طبيعي 100%',
      fit: 'Relaxed Tailored Silhouette',
      fitArabic: 'قصّة عصرية مريحة مع بنطال واسع',
      care: 'Dry clean or gentle hand wash in cold water',
      careArabic: 'تنظيف جاف أو غسيل يدوي لطيف بالماء البارد',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع بأيدي مصرية محترفة في القاهرة',
      modelInfo: 'Model is 174cm wearing size S',
      modelInfoArabic: 'العارضة ترتدي مقاس S بطول 174 سم',
    },
    description:
      'Elevate your daily elegance with our signature two-piece Linen Set. Tailored with breathable organic linen, designed with clean lapels and relaxed straight-leg trousers that flow effortlessly.',
    descriptionArabic:
      'ارتقي بأناقتكِ اليومية مع طقم الكتان الطبيعي الفاخر المكون من قطعتين. مصمم من أنقى خامات الكتان الفرنسي المعالج بقصّة عصرية مريحة مع بنطال واسع وتفاصيل أنيقة تمنحكِ حضوراً ساحراً وانسيابياً في كل خطوة.',
    imageUrls: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
  {
    id: 'prod-pleated-dress-2',
    name: 'PLEATED DRESS',
    nameArabic: 'فستان ماكسي بليسيه كشمير',
    category: 'dresses',
    categoryArabic: 'فساتين',
    price: 520.0,
    stockQuantity: 18,
    colors: [
      { name: 'Warm Taupe', nameArabic: 'بني دافئ', hex: '#B67355' },
      { name: 'Champagne Sand', nameArabic: 'شامبين رملي', hex: '#DCC9A6' },
      { name: 'Midnight Black', nameArabic: 'أسود داكن', hex: '#1F1F1F' },
    ],
    sizes: ['S', 'M', 'L'],
    specs: {
      fabric: 'Premium Micro-Pleat Chiffon & Satin Lining',
      fabricArabic: 'شيفون بليسيه مايكرو فاخر مع بطانة ساتان ناعمة',
      fit: 'Flattering A-Line Midi Cut with belted waist',
      fitArabic: 'قصّة A-Line انسيابية مع حزام خصر متناسق',
      care: 'Professional dry clean only',
      careArabic: 'تنظيف جاف متخصص فقط للحفاظ على الطيات',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع في مصر',
      modelInfo: 'Model is 175cm wearing size M',
      modelInfoArabic: 'العارضة ترتدي مقاس M بطول 175 سم',
    },
    description:
      'A masterpiece of feminine grace. Fine accordion pleats create mesmerizing movement with every step, paired with delicate cuffs and an adjustable silhouette.',
    descriptionArabic:
      'تحفة فنية تفيض بالأنوثة والجاذبية. طيات البليسيه المتقنة تخلق حركة ساحرة مع كل خطوة، مع أكمام محاكة بعناية وحزام خصر يعزز قوامكِ لمظهر لا ينسى في أرقى المناسبات.',
    imageUrls: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
  {
    id: 'prod-oversize-shirt-3',
    name: 'OVERSIZE SHIRT',
    nameArabic: 'قميص أوفرسايز بوبلين قطن',
    category: 'tops',
    categoryArabic: 'بلوزات وتوبات',
    price: 310.0,
    stockQuantity: 45,
    colors: [
      { name: 'Alabaster White', nameArabic: 'أبيض عاجي', hex: '#F6F3EE' },
      { name: 'Terracotta Rust', nameArabic: 'تيراكوتا برونزي', hex: '#B67355' },
      { name: 'Classic Black', nameArabic: 'أسود كلاسيكي', hex: '#1F1F1F' },
    ],
    sizes: ['Free Size (S-XL)'],
    specs: {
      fabric: '100% Egyptian Crisp Poplin Cotton',
      fabricArabic: 'قطن بوبلين مصري فاخر 100%',
      fit: 'Contemporary Oversized Drape',
      fitArabic: 'قصّة أوفرسايز متهدلة وعصرية',
      care: 'Machine wash delicate at 30°C',
      careArabic: 'غسيل في الغسالة على برنامج لطيف 30 درجة مئوية',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع في مصر',
      modelInfo: 'Model is 172cm wearing Free Size',
      modelInfoArabic: 'العارضة ترتدي مقاس موحد بطول 172 سم',
    },
    description:
      'The quintessential luxury wardrobe foundation. Tailored with premium Egyptian cotton, structured drop shoulders, mother-of-pearl finish buttons, and an elongated curved hem.',
    descriptionArabic:
      'القطعة الأساسية التي لا غنى عنها في خزانتكِ الأنيقة. محاكة من أجود أنواع القطن المصري المعالج مع ياقة متناسقة وأكتاف منسدلة وأزرار صدفية تمنحكِ مظهراً مريحاً وجذاباً.',
    imageUrls: [
      'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
  {
    id: 'prod-wide-leg-pants-4',
    name: 'WIDE LEG PANTS',
    nameArabic: 'بنطال واسع بكسرات خصر عالي',
    category: 'bottoms',
    categoryArabic: 'بناطيل وتنانير',
    price: 380.0,
    stockQuantity: 30,
    colors: [
      { name: 'Espresso Charcoal', nameArabic: 'رمادي إسبريسو', hex: '#2A2A2A' },
      { name: 'Camel Tan', nameArabic: 'جملي دافئ', hex: '#C4AE88' },
      { name: 'Off-White Cream', nameArabic: 'أوف وايت كريمي', hex: '#F6F3EE' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    specs: {
      fabric: 'Tailored Twill Suiting Blend',
      fabricArabic: 'مزيج تويل البدلات الإيطالي المتقن',
      fit: 'High-Waist Wide Pleated Leg',
      fitArabic: 'خصر عالي مع أرجل واسعة وكسرات أمامية',
      care: 'Cool iron, machine wash gentle',
      careArabic: 'كوي بحرارة متوسطة، غسيل غسالة لطيف',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع في مصر',
      modelInfo: 'Model is 176cm wearing size S',
      modelInfoArabic: 'العارضة ترتدي مقاس S بطول 176 سم',
    },
    description:
      'Impeccably tailored high-waisted trousers featuring front knife pleats and an ultra-flattering wide leg profile. Designed for commanding presence and effortless comfort.',
    descriptionArabic:
      'بنطال بتفصيل خياطة رفيع المستوى يتميز بخصر مرتفع مزين بكسرات أمامية حادة وقصة أرجل واسعة تضفي لمسة من الوقار والأناقة العصرية على إطلالاتكِ اليومية والمسائية.',
    imageUrls: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
  {
    id: 'prod-blazer-jacket-5',
    name: 'BLAZER JACKET',
    nameArabic: 'بليزر كلاسيكي محبوك بأزرار ذهبية',
    category: 'outerwear',
    categoryArabic: 'بليزر وجواكت',
    price: 560.0,
    discountPrice: 510.0,
    stockQuantity: 15,
    colors: [
      { name: 'Almond Beige', nameArabic: 'بيج لوزي', hex: '#DCC9A6' },
      { name: 'Deep Jet Black', nameArabic: 'أسود فحمي', hex: '#1F1F1F' },
      { name: 'Warm Terracotta', nameArabic: 'تيراكوتا دافئ', hex: '#B67355' },
    ],
    sizes: ['S', 'M', 'L'],
    specs: {
      fabric: 'Fine Wool-Blend Structured Suiting',
      fabricArabic: 'مزيج صوف فاخر مبطن بالساتان الناعم',
      fit: 'Sharp Tailored Double-Breasted Cut',
      fitArabic: 'قصّة بليزر دبل بريستيد بتفصيل راقي',
      care: 'Specialist dry clean only',
      careArabic: 'تنظيف جاف متخصص فقط',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع في مصر',
      modelInfo: 'Model is 177cm wearing size S',
      modelInfoArabic: 'العارضة ترتدي مقاس S بطول 177 سم',
    },
    description:
      'Power dressing refined with feminine softness. Structured padded shoulders, peak lapels, and custom matte tortoiseshell buttons make this blazer the ultimate statement layer.',
    descriptionArabic:
      'القطعة المثالية للتألق بإطلالة فخمة وقوية في آن واحد. مصمم بأكتاف مبطنة بدقة وياقة رسمية حادة مع أزرار ذهبية فاخرة وبطانة حريرية كاملة لتوفير أقصى درجات الراحة.',
    imageUrls: [
      'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
  {
    id: 'prod-satin-dress-6',
    name: 'SATIN DRESS',
    nameArabic: 'فستان ساتان حريري مسائي',
    category: 'dresses',
    categoryArabic: 'فساتين',
    price: 490.0,
    stockQuantity: 22,
    colors: [
      { name: 'Midnight Onyx', nameArabic: 'أونيكس ليلي', hex: '#1F1F1F' },
      { name: 'Champagne Silk', nameArabic: 'حرير شامبين', hex: '#DCC9A6' },
      { name: 'Terracotta Ember', nameArabic: 'تيراكوتا محمر', hex: '#B67355' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    specs: {
      fabric: 'Heavyweight Lustrous Liquid Satin',
      fabricArabic: 'ساتان سائل ثقيل بلمعة لؤلؤية طبيعية',
      fit: 'Bias-Cut Slip Silhouette',
      fitArabic: 'قصّة بايس كات تحتضن القوام برقة',
      care: 'Gentle hand wash inside out, cool iron',
      careArabic: 'غسيل يدوي لطيف مقلوباً، كوي على البارد',
      origin: 'Crafted in Egypt',
      originArabic: 'صنع في مصر',
      modelInfo: 'Model is 173cm wearing size S',
      modelInfoArabic: 'العارضة ترتدي مقاس S بطول 173 سم',
    },
    description:
      'Cut on the bias to drape like a second skin. Features an alluring low back, adjustable delicate straps, and a subtle side split for fluid evening elegance.',
    descriptionArabic:
      'فستان سهرة ينسدل كالحرير على قوامكِ بنعومة تامة. يتميز بلمعة الساتان الساحرة وظهر مكشوف برقة مع فتحة جانبية رقيقة تعكس الفخامة والأنوثة في سهراتكِ الخاصة.',
    imageUrls: [
      'https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=900&auto=format&fit=crop&q=85',
    ],
    featured: true,
    isNewArrival: true,
  },
];
